/**
 * Login Page - Generated by Enhanced Page Assembler
 *
 * Automatically generated from Figma screen: Login
 * Uses enhanced component generation with proper styling and layout
 */

"use client"

import React from "react"
import { Button } from "@/components/navigation/button"
import { Input } from "@/components/forms/input"
import { Card } from "@/components/display/card"

export default function LoginPage() {
  return (
    <div className="min-h-screen bg-gray-100">
      <div className="w-full h-full">
        <div className="flex flex-row items-center justify-center w-full min-h-screen bg-gray-50 p-8 gap-8">
          {/* Illustration Side */}
          <div className="flex-1 max-w-2xl flex items-center justify-center">
            <div className="bg-gray-100 rounded-lg p-8 flex items-center justify-center" style={{ minHeight: '400px', backgroundColor: '#f0f0f0', borderRadius: '8px' }}>
              <span className="text-gray-600 text-lg">Illustration</span>
            </div>
          </div>

          {/* Form Card Side */}
          <div className="flex-1 max-w-md w-full">
            <div className="bg-white rounded-lg shadow-lg p-8" style={{ backgroundColor: '#ffffff', borderRadius: '8px', padding: '2rem', boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)' }}>
              <div className="flex flex-col items-stretch space-y-4">

                <h1 className="text-2xl font-bold text-gray-900 mb-6" style={{ fontSize: '2rem', fontWeight: 'bold', color: '#2e2e2e', textAlign: 'left', backgroundColor: 'transparent' }}>
                  Welcome to Design School
                </h1>
                <Button
                  variant="google"
                  className="w-full flex items-center justify-center gap-2 border rounded-lg"
                  style={{ padding: '12px 16px', fontSize: '16px', fontWeight: '500' }}
                >
                  Continue with Google
                </Button>
                <Button
                  variant="facebook"
                  className="w-full flex items-center justify-center gap-2 border rounded-lg"
                  style={{ padding: '12px 16px', fontSize: '16px', fontWeight: '500' }}
                >
                  Continue with Facebook
                </Button>
                <div className="text-gray-600 text-center my-4" style={{ fontSize: '1rem', color: '#6b7280', textAlign: 'center' }}>
                  or
                </div>
                <Input
                  type="password"
                  placeholder="Enter your password"
                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  style={{ padding: '12px 16px', fontSize: '16px' }}
                />
                <Input
                  type="email"
                  placeholder="Enter your email"
                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  style={{ padding: '12px 16px', fontSize: '16px' }}
                />
                <Input
                  type="password"
                  placeholder="Enter your password"
                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  style={{ padding: '12px 16px', fontSize: '16px' }}
                />
                <Button
                  variant="primary"
                  className="w-full bg-primary-500 text-white hover:bg-primary-600 rounded-lg"
                  style={{ backgroundColor: '#6257db', padding: '12px 24px', fontSize: '16px', fontWeight: '500' }}
                  type="submit"
                >
                  Login
                </Button>
                <div className="flex items-center justify-between w-full">
                  <label className="flex items-center space-x-2 text-sm text-gray-600" style={{ textAlign: 'left', alignSelf: 'flex-start' }}>
                    <input type="checkbox" className="rounded border-gray-300" />
                    <span>Remember me</span>
                  </label>
                  <button
                    className="text-primary underline text-sm"
                    style={{ color: '#6257db', textDecoration: 'underline', fontSize: '14px', textAlign: 'right' }}
                  >
                    Forgot Password?
                  </button>
                </div>
                <div className="text-sm text-gray-600 text-left mt-4" style={{ fontSize: '0.875rem', color: '#000000', textAlign: 'left', backgroundColor: 'transparent' }}>
                  Don't have an account? Register
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}