/**
 * Button Component - Generated by Stage 3 Component Generator (Figma-Enhanced)
 *
 * button - Navigation component enhanced with Figma design properties
 * Uses actual design values from Figma instead of static patterns
 */

"use client"

import * as React from "react"

import { cva, type VariantProps } from "class-variance-authority"

// Loading spinner component
const LoadingSpinner = () => (
  <svg
    className="animate-spin h-4 w-4 text-current opacity-70"
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
  >
    <circle
      className="opacity-25"
      cx="12"
      cy="12"
      r="10"
      stroke="currentColor"
      strokeWidth="4"
    />
    <path
      className="opacity-75"
      fill="currentColor"
      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
    />
  </svg>
)

// Button variants using CVA with Figma design tokens
const buttonVariants = cva(
  // Base classes
  "inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-background",
  {
    variant: {
      default: "bg-primary text-primary hover:opacity-90",
      primary: "bg-primary text-primary hover:opacity-90",
      destructive: "bg-red-600 text-white hover:opacity-90",
      outline: "border border-gray-200 bg-white hover:bg-gray-50",
      secondary: "bg-gray-100 text-gray-900 hover:bg-gray-200",
      ghost: "hover:bg-gray-100",
      link: "underline-offset-4 hover:underline text-primary",
      success: "bg-success text-success hover:opacity-90",
      warning: "bg-warning text-warning hover:opacity-90",
    },
    size: {
      default: "h-10 p-3 space-y-3 gap-3",
      sm: "h-9 p-3 space-y-3 gap-3 rounded-md",
      md: "h-10 p-3 space-y-3 gap-3",
      lg: "h-11 p-4 space-y-4 gap-4 rounded-md",
      icon: "h-10 w-10",
    },
  }
)
// Export Button props interface matching Stage 2 button component
export interface ButtonProps extends React.HTMLAttributes<HTMLButtonElement>, VariantProps<typeof buttonVariants> {
  // Stage 2 button component interface
  width?: string | number
  height?: string | number
  position?: { x?: number; y?: number }
  backgroundColor?: string
  backgroundOpacity?: number
  borderRadius?: string | number
  display?: "block" | "inline" | "inline-block" | "flex" | "grid" | "none"
  overflow?: "visible" | "hidden" | "scroll" | "auto"
  style?: React.CSSProperties
  children?: React.ReactNode
  id?: string
  testId?: string
  // Enhanced button specific props
  disabled?: boolean
  loading?: boolean
  onClick?: (event: React.MouseEvent) => void
  type?: "button" | "submit" | "reset"
}
// Main Button component
const Button = React.forwardRef<  HTMLButtonElement,  ButtonProps
>(
  ({
  className,
  variant,
  size,
  width,
  height,
  position,
  backgroundColor,
  backgroundOpacity,
  borderRadius,
  display,
  overflow,
  style,
  children,
  id,
  testId,
  disabled = false,
  loading = false,
  onClick,
  type = "button",
  ...props
  }, ref) => {
  // No additional state needed for basic button
  // No additional handlers needed for basic button

  // Combine inline styles
  const inlineStyles: React.CSSProperties = {
    ...style,
    ...(width && { width: typeof width === 'number' ? `${width}px` : width }),
    ...(height && { height: typeof height === 'number' ? `${height}px` : height }),
    ...(backgroundColor && {
      backgroundColor,
      opacity: backgroundOpacity !== undefined ? backgroundOpacity : 1
    }),
    ...(borderRadius && { borderRadius: typeof borderRadius === 'number' ? `${borderRadius}px` : borderRadius }),
    ...(display && { display }),
    ...(overflow && { overflow }),
    ...(position && {
      position: 'absolute' as const,
      left: position.x !== undefined ? `${position.x}px` : undefined,
      top: position.y !== undefined ? `${position.y}px` : undefined
    })
  }

  const componentClasses = [
    buttonVariants({      variant, size    }),
    className || ''
  ].filter(Boolean).join(' ')

  return (
    <button
      ref={ref}
      className={componentClasses}
      style={inlineStyles}
      id={id}
      data-testid={testId}
      disabled={disabled || loading}
      onClick={onClick}
      type={type}
      {...props}
    >
      {loading ? (
        <>
          <LoadingSpinner />
          {children && <span className="ml-2">{children}</span>}
        </>
      ) : (
        children
      )}
    </button>
  )
  }
)

Button.displayName = "Button"

export { Button, buttonVariants }