/**
 * Forgot-Password Component - Generated by Stage 3 Component Generator (Figma-Enhanced)
 *
 * forgot-password - Navigation component enhanced with Figma design properties
 * Uses actual design values from Figma instead of static patterns
 */

"use client"

import * as React from "react"

import { cva, type VariantProps } from "class-variance-authority"

// Navigation component variants using CVA with Figma design tokens
const forgotPasswordVariants = cva(
  // Base classes
  "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50",
  {
    variant: {
      default: "text-primary underline-offset-4 hover:underline",
      destructive: "text-destructive underline-offset-4 hover:underline",
      outline: "border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground",
      secondary: "text-secondary-foreground underline-offset-4 hover:underline",
      ghost: "hover:bg-accent hover:text-accent-foreground",
      link: "text-primary underline-offset-4 hover:underline",
    },
    size: {
      default: "h-9 px-4 py-2",
      sm: "h-8 rounded-md px-3 text-xs",
      lg: "h-10 rounded-md px-8",
      icon: "h-9 w-9",
    },
  }
)

// Export Forgot-Password props interface matching Stage 2 forgot-password component
export interface ForgotPasswordProps extends
  React.HTMLAttributes<HTMLButtonElement>,
  VariantProps<typeof forgotPasswordVariants>
{
  // Stage 2 forgot-password component interface
  width?: string | number
  height?: string | number
  position?: { x?: number; y?: number }
  backgroundColor?: string
  backgroundOpacity?: number
  borderRadius?: string | number
  display?: "block" | "inline" | "inline-block" | "flex" | "grid" | "none"
  overflow?: "visible" | "hidden" | "scroll" | "auto"
  style?: React.CSSProperties
  children?: React.ReactNode
  id?: string
  testId?: string
  disabled?: boolean
  loading?: boolean
  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void
  type?: "button" | "submit" | "reset"
}

// Main Forgot-Password component
const ForgotPassword = React.forwardRef<
  HTMLButtonElement,
  ForgotPasswordProps
>(
  ({
  className,
  variant,
  size,
  width,
  height,
  position,
  backgroundColor,
  backgroundOpacity,
  borderRadius,
  display,
  overflow,
  style,
  children,
  id,
  testId,
  disabled = false,
  loading = false,
  onClick,
  type = "button",
  ...props
  }, ref) => {

  // No additional state needed for basic forgot-password
  // No additional handlers needed for basic forgot-password

  // Combine inline styles
  const inlineStyles: React.CSSProperties = {
    ...style,
    ...(width && { width: typeof width === 'number' ? `${width}px` : width }),
    ...(height && { height: typeof height === 'number' ? `${height}px` : height }),
    ...(backgroundColor && {
      backgroundColor,
      opacity: backgroundOpacity !== undefined ? backgroundOpacity : 1
    }),
    ...(borderRadius && { borderRadius: typeof borderRadius === 'number' ? `${borderRadius}px` : borderRadius }),
    ...(display && { display }),
    ...(overflow && { overflow }),
    ...(position && {
      position: 'absolute' as const,
      left: position.x !== undefined ? `${position.x}px` : undefined,
      top: position.y !== undefined ? `${position.y}px` : undefined
    })
  }
  const componentClasses = [
    forgotPasswordVariants({
      variant, size
    }),
    className || ''
  ].filter(Boolean).join(' ')
  return (
    <button
      ref={ref}
      className={componentClasses}
      style={inlineStyles}
      id={id}
      data-testid={testId}
      disabled={disabled || loading}
      onClick={onClick}
      type={type}
      {...props}
    >
      {loading ? (
        <>
          <span className="animate-pulse">Loading...</span>
          {children && <span className="ml-2">{children}</span>}
        </>
      ) : (
        children
      )}
    </button>
  )
  }
)

ForgotPassword.displayName = "Forgot-Password"
export { ForgotPassword, forgotPasswordVariants }