/**
 * Login Component - Generated by Stage 3 Component Generator (Figma-Enhanced)
 *
 * login - Navigation component enhanced with Figma design properties
 * Uses actual design values from Figma instead of static patterns
 */

"use client"

import * as React from "react"

import { cva, type VariantProps } from "class-variance-authority"

// Loading spinner component
const LoadingSpinner = () => (
  <svg
    className="animate-spin h-4 w-4 text-current opacity-70"
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
  >
    <circle
      className="opacity-25"
      cx="12"
      cy="12"
      r="10"
      stroke="currentColor"
      strokeWidth="4"
    />
    <path
      className="opacity-75"
      fill="currentColor"
      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
    />
  </svg>
)

// Navigation component variants using CVA with Figma design tokens
const loginVariants = cva(
  // Base classes
  "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50",
  {
    variant: {
      default: "bg-primary text-primary-foreground shadow hover:bg-primary/90",
      destructive:
        "bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90",
      outline:
        "border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground",
      secondary:
        "bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80",
      ghost: "hover:bg-accent hover:text-accent-foreground",
      link: "text-primary underline-offset-4 hover:underline",
    },
    size: {
      default: "h-9 px-4 py-2",
      sm: "h-8 rounded-md px-3 text-xs",
      lg: "h-10 rounded-md px-8",
      icon: "h-9 w-9",
    },
  }
)

// Export Login props interface matching Stage 2 login component
export interface LoginProps extends
  React.HTMLAttributes<HTMLButtonElement>,
  VariantProps<typeof loginVariants>
{
  // Stage 2 login component interface
  width?: string | number
  height?: string | number
  position?: { x?: number; y?: number }
  backgroundColor?: string
  backgroundOpacity?: number
  borderRadius?: string | number
  display?: "block" | "inline" | "inline-block" | "flex" | "grid" | "none"
  overflow?: "visible" | "hidden" | "scroll" | "auto"
  style?: React.CSSProperties
  children?: React.ReactNode
  id?: string
  testId?: string
}

// Main Login component
const Login = React.forwardRef<
  HTMLButtonElement,
  LoginProps
>(
  ({
  className,
  variant,
  size,
  width,
  height,
  position,
  backgroundColor,
  backgroundOpacity,
  borderRadius,
  display,
  overflow,
  style,
  children,
  id,
  testId,
  disabled = false,
  loading = false,
  onClick,
  type = "button",
  ...props
  }, ref) => {

  // No additional state needed for basic login
  // No additional handlers needed for basic login

  // Combine inline styles
  const inlineStyles: React.CSSProperties = {
    ...style,
    ...(width && { width: typeof width === 'number' ? `${width}px` : width }),
    ...(height && { height: typeof height === 'number' ? `${height}px` : height }),
    ...(backgroundColor && {
      backgroundColor,
      opacity: backgroundOpacity !== undefined ? backgroundOpacity : 1
    }),
    ...(borderRadius && { borderRadius: typeof borderRadius === 'number' ? `${borderRadius}px` : borderRadius }),
    ...(display && { display }),
    ...(overflow && { overflow }),
    ...(position && {
      position: 'absolute' as const,
      left: position.x !== undefined ? `${position.x}px` : undefined,
      top: position.y !== undefined ? `${position.y}px` : undefined
    })
  }
  const componentClasses = [
    loginVariants({
      variant, size
    }),
    className || ''
  ].filter(Boolean).join(' ')
  return (
    <button
      ref={ref}
      className={componentClasses}
      style={inlineStyles}
      id={id}
      data-testid={testId}
      disabled={disabled || loading}
      onClick={onClick}
      type={type}
      {...props}
    >
      {loading ? (
        <>
          <LoadingSpinner />
          {children && <span className="ml-2">{children}</span>}
        </>
      ) : (
        children
      )}
    </button>
  )
  }
)

Login.displayName = "Login"
export { Login, loginVariants }