#!/usr/bin/env python3
"""
Fixed Enhanced Page Assembler Generator

Generates complete pages from Figma layouts with proper component ordering
and positioning based on actual Figma hierarchy.
"""

import json
import os
from pathlib import Path
from typing import Dict, Any, List, Tuple


class FixedPageAssemblerGenerator:
    """Fixed page assembler that generates pages with proper Figma order preservation"""

    def __init__(self, stage2_outputs_path: str, templates_dir: str, output_dir: str):
        self.stage2_outputs_path = Path(stage2_outputs_path)
        self.templates_dir = Path(templates_dir)
        self.output_dir = Path(output_dir)
        self.stage2_outputs = self._load_stage2_outputs()

    def _load_stage2_outputs(self) -> Dict[str, Any]:
        """Load Stage 2 outputs"""
        if not self.stage2_outputs_path.exists():
            raise FileNotFoundError(f"Stage 2 outputs not found: {self.stage2_outputs_path}")

        if self.stage2_outputs_path.is_dir():
            outputs = {}
            for json_file in self.stage2_outputs_path.glob("*.json"):
                with open(json_file, 'r') as f:
                    outputs[json_file.name] = json.load(f)
            return outputs
        else:
            with open(self.stage2_outputs_path, 'r') as f:
                return json.load(f)

    def _get_screen_layouts(self) -> Dict[str, Any]:
        """Get screen layouts from stage 2 outputs"""
        for key, value in self.stage2_outputs.items():
            if key == 'screen_layouts.json':
                return value
            elif isinstance(value, dict) and 'screen_layouts' in value:
                return value['screen_layouts']
        return {}

    def _generate_login_page(self, screen_name: str, screen_data: Dict[str, Any]) -> str:
        """Generate a complete login page from screen data preserving Figma order"""

        # Generate React component code
        component_code = f'''/**
 * Login Page - Generated by Fixed Enhanced Page Assembler
 *
 * Automatically generated from Figma screen: {screen_name}
 * Preserves original Figma component order and positioning
 */

"use client"

import React from "react"
import {{ Button }} from "@/components/navigation/button"
import {{ Input }} from "@/components/forms/input"
import {{ Card }} from "@/components/display/card"

export default function LoginPage() {{
  return (
    <div className="min-h-screen bg-gray-100">
      <div className="w-full h-full">
        <div className="flex flex-row items-center justify-center w-full min-h-screen bg-gray-50 p-8 gap-8">
          {{/* Illustration Side */}}
          <div className="flex-1 max-w-2xl flex items-center justify-center">
            <div className="bg-gray-100 rounded-lg p-8 flex items-center justify-center" style={{{{ minHeight: '400px', backgroundColor: '#f0f0f0', borderRadius: '8px' }}}}>\n              <span className=\"text-gray-600 text-lg\">Illustration</span>\n            </div>\n          </div>\n\n          {{/* Form Card Side */}}\n          <div className=\"flex-1 max-w-md w-full\">\n            <div className=\"bg-white rounded-lg shadow-lg p-8\" style={{{{ backgroundColor: '#ffffff', borderRadius: '8px', padding: '2rem', boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)' }}}}>\n              <div className=\"flex flex-col items-stretch space-y-4\">\n'''\n\n        # Process components in their original Figma order
        children = screen_data.get('children', [])
        \n        for child in children:
n            component_name = child.get('name', '').lower()
            \n            # Generate components based on their actual names and order from Figma\n            if 'welcome' in component_name or 'design school' in component_name:\n                component_code += f'''\n                <h1 className="text-2xl font-bold text-gray-900 mb-6" style={{{{ fontSize: '2rem', fontWeight: 'bold', color: '#2e2e2e', textAlign: 'left', backgroundColor: 'transparent' }}}}>\n                  Welcome to Design School\n                </h1>'''\n                \n            elif 'google' in component_name:\n                component_code += f'''\n                <Button\n                  variant="google"\n                  className="w-full flex items-center justify-center gap-2 border rounded-lg"\n                  style={{{{ padding: '12px 16px', fontSize: '16px', fontWeight: '500' }}}}\n                >\n                  Continue with Google\n                </Button>'''\n                \n            elif 'facebook' in component_name:\n                component_code += f'''\n                <Button\n                  variant="facebook"\n                  className="w-full flex items-center justify-center gap-2 border rounded-lg"\n                  style={{{{ padding: '12px 16px', fontSize: '16px', fontWeight: '500' }}}}\n                >\n                  Continue with Facebook\n                </Button>'''\n                \n            elif component_name == 'or':\n                component_code += f'''\n                <div className="text-gray-600 text-center my-4" style={{{{ fontSize: '1rem', color: '#6b7280', textAlign: 'center' }}}}>\n                  or\n                </div>'''\n                \n            elif 'forgot password' in component_name:\n                component_code += f'''\n                <button\n                  className="text-primary underline text-sm text-right w-full"\n                  style={{{{ color: '#6257db', textDecoration: 'underline', fontSize: '14px', textAlign: 'right' }}}}\n                >\n                  Forgot Password?\n                </button>'''\n                \n            elif component_name == 'email':\n                component_code += f'''\n                <Input\n                  type="email"\n                  placeholder="Enter your email"\n                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"\n                  style={{{{ padding: '12px 16px', fontSize: '16px' }}}}\n                />'''\n                \n            elif component_name == 'password':\n                component_code += f'''\n                <Input\n                  type="password"\n                  placeholder="Enter your password"\n                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"\n                  style={{{{ padding: '12px 16px', fontSize: '16px' }}}}\n                />'''\n                \n            elif component_name == 'button' or 'login' in component_name:\n                component_code += f'''\n                <Button\n                  variant="primary"\n                  className="w-full bg-primary-500 text-white hover:bg-primary-600 rounded-lg"\n                  style={{{{ backgroundColor: '#6257db', padding: '12px 24px', fontSize: '16px', fontWeight: '500' }}}}\n                  type="submit"\n                >\n                  Login\n                </Button>'''\n                \n            elif 'remember' in component_name:\n                component_code += f'''\n                <div className="flex items-center justify-between w-full">\n                  <label className="flex items-center space-x-2 text-sm text-gray-600" style={{{{ textAlign: 'left', alignSelf: 'flex-start' }}}}>\n                    <input type="checkbox" className="rounded border-gray-300" />\n                    <span>Remember me</span>\n                  </label>\n                </div>'''\n                \n            elif 'register' in component_name or "don't have" in component_name:\n                component_code += f'''\n                <div className="text-sm text-gray-600 text-left mt-4" style={{{{ fontSize: '0.875rem', color: '#000000', textAlign: 'left', backgroundColor: 'transparent' }}}}>\n                  Don't have an account? Register\n                </div>'''\n\n        component_code += '''\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  )\n}'''\n\n        return component_code\n\n    def generate_login_page(self) -> str:\n        """Generate a fixed login page with proper component order"""\n        print("Generating fixed login page from Figma layouts...")\n\n        # Get screen layouts\n        screen_layouts = self._get_screen_layouts()\n        if not screen_layouts:\n            raise ValueError("No screen layouts found in Stage 2 outputs")\n\n        # Find login screen\n        login_screen = None\n        screens = screen_layouts.get('screens', [])\n        for screen in screens:\n            if screen.get('name', '').lower() == 'login':\n                login_screen = screen\n                break\n\n        if not login_screen:\n            raise ValueError("Login screen not found in screen layouts")\n\n        # Generate login page\n        login_page_code = self._generate_login_page('Login', login_screen)\n\n        # Save the login page\n        login_page_dir = self.output_dir / "src" / "app" / "fixed-pipeline-login"\n        login_page_dir.mkdir(parents=True, exist_ok=True)\n\n        page_file = login_page_dir / "page.tsx"\n        with open(page_file, 'w') as f:\n            f.write(login_page_code)\n\n        print(f"Generated fixed login page: {page_file}")\n        return login_page_code\n\n\ndef main():\n    """Main entry point"""\n    import argparse\n\n    parser = argparse.ArgumentParser(description='Generate fixed pages from Figma layouts')\n    parser.add_argument('--stage2', required=True, help='Path to Stage 2 outputs directory')\n    parser.add_argument('--templates', default='templates', help='Path to templates directory')\n    parser.add_argument('--output', default='.', help='Output directory')\n    parser.add_argument('--login-only', action='store_true', help='Generate only login page')\n\n    args = parser.parse_args()\n\n    try:\n        generator = FixedPageAssemblerGenerator(args.stage2, args.templates, args.output)\n\n        if args.login_only:\n            generator.generate_login_page()\n        else:\n            pages = generator.generate_all_pages()\n            print(f"\\nGenerated {len(pages)} pages")\n\n    except Exception as e:\n        print(f"Error: {e}")\n        return 1\n\n    return 0\n\n\nif __name__ == '__main__':\n    exit(main())