#!/usr/bin/env python3
"""
Post-Generation CSS Fix Script

This script analyzes generated components and automatically generates
missing CSS classes to ensure all design tokens are properly styled.
It runs after component generation to fix any CSS issues.
"""

import json
import os
import sys
from pathlib import Path
from typing import Dict, Any, Set
import argparse

# Import CSS validator
from css_validator import CSSValidator


class PostGenerationCSSFix:
    """Automated CSS generation for design tokens"""

    def __init__(self, project_root: str):
        self.project_root = Path(project_root)
        self.css_validator = CSSValidator()
        self.component_dirs = [
            self.project_root / "src" / "components" / "navigation",
            self.project_root / "src" / "components" / "forms",
            self.project_root / "src" / "components" / "display",
            self.project_root / "src" / "components" / "feedback",
            self.project_root / "src" / "components" / "ui",
        ]
        self.globals_css_path = self.project_root / "src" / "app" / "globals.css"

    def analyze_all_components(self) -> Dict[str, Any]:
        """Analyze all components and find missing CSS classes"""
        all_classes = set()
        all_missing_classes = set()
        all_invalid_classes = set()
        component_results = {}

        print("🔍 Analyzing all components for CSS classes...")

        for component_dir in self.component_dirs:
            if not component_dir.exists():
                continue

            for component_file in component_dir.glob("*.tsx"):
                try:
                    with open(component_file, 'r', encoding='utf-8') as f:
                        content = f.read()

                    classes = self.css_validator.extract_classes_from_component(content)
                    missing, invalid = self.css_validator.validate_design_token_classes(classes)

                    component_results[str(component_file)] = {
                        'classes': classes,
                        'missing': missing,
                        'invalid': invalid
                    }

                    all_classes.update(classes)
                    all_missing_classes.update(missing)
                    all_invalid_classes.update(invalid)

                except Exception as e:
                    print(f"  Error analyzing {component_file}: {e}")
                    continue

        return {
            'total_classes': len(all_classes),
            'total_missing': len(all_missing_classes),
            'total_invalid': len(all_invalid_classes),
            'missing_classes': all_missing_classes,
            'invalid_classes': all_invalid_classes,
            'component_results': component_results
        }

    def generate_css_fixes(self, missing_classes: Set[str]) -> str:
        """Generate CSS rules for missing classes"""
        css_content = [
            "/* Auto-generated CSS fixes for design tokens */",
            "/* Generated by Post-Generation CSS Fix - Do not edit manually */",
            "/* Generated on: " + __import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S') + " */",
            ""
        ]

        for class_name in sorted(missing_classes):
            css_rule = self.css_validator._generate_css_rule(class_name)
            if css_rule:
                css_content.append(css_rule)

        return '\n'.join(css_content)

    def apply_css_fixes(self, css_content: str):
        """Apply CSS fixes to the globals.css file"""
        if not css_content.strip():
            print("✅ No CSS fixes needed")
            return True

        try:
            # Read existing CSS
            existing_css = ""
            if self.globals_css_path.exists():
                with open(self.globals_css_path, 'r') as f:
                    existing_css = f.read()

            # Check if fixes are already applied
            if css_content.strip() in existing_css:
                print("✅ CSS fixes already applied")
                return True

            # Append fixes
            with open(self.globals_css_path, 'a') as f:
                f.write("\n\n")
                f.write(css_content)

            print(f"✅ Applied CSS fixes to: {self.globals_css_path}")
            return True

        except Exception as e:
            print(f"❌ Error applying CSS fixes: {e}")
            return False

    def validate_tailwind_config(self) -> bool:
        """Check if Tailwind config exists and has design tokens"""
        tailwind_config_path = self.project_root / "tailwind.config.js"

        if not tailwind_config_path.exists():
            print("❌ Tailwind config not found")
            return False

        try:
            with open(tailwind_config_path, 'r') as f:
                config_content = f.read()

            # Check for design token configuration
            required_patterns = [
                'primary',
                'success',
                'warning',
                'error'
            ]

            missing_patterns = []
            for pattern in required_patterns:
                if pattern not in config_content:
                    missing_patterns.append(pattern)

            if missing_patterns:
                print(f"⚠️  Tailwind config missing design tokens: {missing_patterns}")
                return False

            print("✅ Tailwind config looks good")
            return True

        except Exception as e:
            print(f"❌ Error validating Tailwind config: {e}")
            return False

    def generate_report(self, analysis_results: Dict[str, Any]) -> str:
        """Generate a comprehensive report of CSS issues"""
        report_lines = [
            "# Post-Generation CSS Fix Report",
            "",
            f"Generated on: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "## Summary",
            f"- Total CSS classes found: {analysis_results['total_classes']}",
            f"- Missing design token classes: {analysis_results['total_missing']}",
            f"- Potentially invalid classes: {analysis_results['total_invalid']}",
            "",
        ]

        if analysis_results['missing_classes']:
            report_lines.extend([
                "## Missing Design Token Classes",
                "These classes need to be generated:",
                ""
            ])
            for cls in sorted(analysis_results['missing_classes']):
                report_lines.append(f"- {cls}")
            report_lines.append("")

        if analysis_results['invalid_classes']:
            report_lines.extend([
                "## Potentially Invalid Classes",
                "These classes may need manual review:",
                ""
            ])
            for cls in sorted(analysis_results['invalid_classes']):
                report_lines.append(f"- {cls}")
            report_lines.append("")

        if analysis_results['component_results']:
            report_lines.extend([
                "## Component Details",
                ""
            ])
            for file_path, results in analysis_results['component_results'].items():
                if results['missing'] or results['invalid']:
                    report_lines.append(f"### {file_path}")
                    if results['missing']:
                        report_lines.append(f"- Missing: {', '.join(results['missing'])}")
                    if results['invalid']:
                        report_lines.append(f"- Invalid: {', '.join(results['invalid'])}")
                    report_lines.append("")

        return '\n'.join(report_lines)

    def run_fix(self, dry_run: bool = False, generate_report: bool = False) -> bool:
        """Run the complete CSS fix process"""
        print("🚀 Starting Post-Generation CSS Fix...")
        print("=" * 50)

        # Validate Tailwind config
        if not self.validate_tailwind_config():
            print("❌ Tailwind config validation failed")
            return False

        # Analyze components
        analysis_results = self.analyze_all_components()

        print(f"📊 Analysis Results:")
        print(f"  Total classes found: {analysis_results['total_classes']}")
        print(f"  Missing design token classes: {analysis_results['total_missing']}")
        print(f"  Potentially invalid classes: {analysis_results['total_invalid']}")

        if analysis_results['missing_classes']:
            print(f"\n🔧 Missing Design Token Classes:")
            for cls in sorted(analysis_results['missing_classes']):
                print(f"  - {cls}")

        if analysis_results['invalid_classes']:
            print(f"\n⚠️  Potentially Invalid Classes:")
            for cls in sorted(analysis_results['invalid_classes']):
                print(f"  - {cls}")

        # Generate CSS fixes
        css_content = self.generate_css_fixes(analysis_results['missing_classes'])

        if dry_run:
            print(f"\n🔍 Dry run - would generate {len(css_content.splitlines())} CSS rules")
            print("Generated CSS:")
            print("-" * 40)
            print(css_content)
            return True

        # Apply fixes
        if css_content.strip():
            success = self.apply_css_fixes(css_content)
            if not success:
                return False

        # Generate report
        if generate_report:
            report = self.generate_report(analysis_results)
            report_path = self.project_root / "css-fix-report.md"
            with open(report_path, 'w') as f:
                f.write(report)
            print(f"📄 Generated report: {report_path}")

        print(f"\n✅ Post-Generation CSS Fix completed successfully!")
        return True


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(description='Post-Generation CSS Fix Script')
    parser.add_argument('--project-root', default='.', help='Project root directory')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be generated without applying changes')
    parser.add_argument('--generate-report', action='store_true', help='Generate detailed report')

    args = parser.parse_args()

    fixer = PostGenerationCSSFix(args.project_root)
    success = fixer.run_fix(dry_run=args.dry_run, generate_report=args.generate_report)

    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()