/**
 * Email Component - Generated by Stage 3 Component Generator (Figma-Enhanced)
 *
 * email - Display component enhanced with Figma design properties
 * Uses actual design values from Figma instead of static patterns
 */

"use client"

import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"

// Display component variants using CVA with Figma design tokens
const emailVariants = cva(
  // Base classes
  "bg-white border-gray-200 border shadow-sm rounded-lg",
  {
    variant: {
      default: "bg-white border-gray-200",
      elevated: "bg-white border-gray-200 shadow-sm",
      outlined: "bg-white border-gray-200",
      filled: "bg-gray-50 border-gray-200",
      success: "bg-success border-success",
      warning: "bg-warning border-warning",
      error: "bg-gray-50 border-gray-200",
      ghost: "bg-transparent border-transparent shadow-none",
    },
    size: {
      sm: "p-3 space-y-3 gap-3",
      md: "p-3 space-y-3 gap-3",
      lg: "p-4 space-y-4 gap-4",
      xl: "p-5 space-y-5 gap-5",
    },
    layout: {
      default: "flex flex-col",
      horizontal: "flex flex-row space-y-3 gap-3",
      stacked: "flex flex-col space-y-3 gap-3",
      grid: "grid grid-cols-1 space-y-3 gap-3",
    }
  }
)

// Export Email props interface matching Stage 2 email component
export interface EmailProps extends
  React.InputHTMLAttributes<HTMLInputElement>,
  VariantProps<typeof emailVariants>
{
  // Stage 2 email component interface
  width?: string | number
  height?: string | number
  position?: { x?: number; y?: number }
  backgroundColor?: string
  backgroundOpacity?: number
  borderRadius?: string | number
  display?: "block" | "inline" | "inline-block" | "flex" | "grid" | "none"
  overflow?: "visible" | "hidden" | "scroll" | "auto"
  style?: React.CSSProperties
  children?: React.ReactNode
  id?: string
  testId?: string
  placeholder?: string
  type?: "email"
}

// Main Email component
const Email = React.forwardRef<
  HTMLInputElement,
  EmailProps
>(
  ({
    className,
    variant,
    size,
    layout,
    width,
    height,
    position,
    backgroundColor,
    backgroundOpacity,
    borderRadius,
    display,
    overflow,
    style,
    id,
    testId,
    placeholder = "Enter your email",
    type = "email",
    ...props
  }, ref) => {

  // No additional state needed for basic email
  // No additional handlers needed for basic email

  // Combine inline styles
  const inlineStyles: React.CSSProperties = {
    ...style,
    ...(width && { width: typeof width === 'number' ? `${width}px` : width }),
    ...(height && { height: typeof height === 'number' ? `${height}px` : height }),
    ...(backgroundColor && {
      backgroundColor,
      opacity: backgroundOpacity !== undefined ? backgroundOpacity : 1
    }),
    ...(borderRadius && { borderRadius: typeof borderRadius === 'number' ? `${borderRadius}px` : borderRadius }),
    ...(display && { display }),
    ...(overflow && { overflow }),
    ...(position && {
      position: 'absolute' as const,
      left: position.x !== undefined ? `${position.x}px` : undefined,
      top: position.y !== undefined ? `${position.y}px` : undefined
    })
  }

  const componentClasses = [
    emailVariants({ variant, size, layout }),
    className || ''
  ].filter(Boolean).join(' ')

  return (
    <input
      ref={ref}
      type={type}
      placeholder={placeholder}
      className={componentClasses}
      style={inlineStyles}
      id={id}
      data-testid={testId}
      {...props}
    />
  )
})

Email.displayName = "Email"

export { Email, emailVariants }