version: "4.0"
markdownExploder: true
evolutionary:
  guidelinesFile: .bmad-core/evolutionary-guidelines.md
  approach: "small-batch-evolutionary"
  maxTasksPerBatch: 3
  agentMode: "telescope-and-compass"
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
  evolutionary: true
  emergentPlanning: true
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
  evolutionary: true
  emergentDesign: true
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - .bmad-core/evolutionary-guidelines.md
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
